name: tests

on:
  push:
    branches:
      - "ci-cd"
  pull_request:
    branches:
      - "master"

jobs:
  cache:
    name: Install and cache dependencies
    runs-on: ubuntu-20.04
    container:
      # github actions/cache@v2 not work on node alpine
      image: node:14.17-stretch-slim
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
  prettier:
    needs: cache
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-stretch-slim
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: "Install dependencies"
        run: npm ci
      - name: Check our source code by prettier
        continue-on-error: true
        run: npm run check:format
  typescript:
    needs: cache
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-stretch-slim
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: "Install dependencies"
        run: npm ci
      - name: TypeScript check
        run: npm run check:types
